// SPDX-License-Identifier: AGPL-3.0-or-later

package brokerauth

import (
	"strings"

	natsserver "github.com/nats-io/nats-server/v2/server"
)

// inboxPrefixRoot is the first token of every per-worker reply-inbox
// prefix. It deliberately does NOT contain a "." so that the whole prefix is
// a single subject token and "<prefix>.>" covers exactly one worker's
// inboxes.
const inboxPrefixRoot = "_INBOX_"

// InboxPrefix returns the reply-inbox subject prefix reserved for workerID.
//
// nats.go's default prefix is the process-global "_INBOX", under which each
// connection takes "_INBOX.<connection-nuid>.*". Granting a worker "_INBOX.>"
// would therefore let it subscribe to every other client's reply inbox on
// this broker. Work leases are core-NATS request/reply and the batch is
// delivered with msg.Respond (internal/bus/lease.go), so one enrolled worker
// could read every other worker's assignment — the OnRun command line and
// arguments, embedded file contents, job and task parameters, environment
// variables, the path map and the isolation account — plus the JetStream API
// replies to sqi-server's own client, without ever leasing a task itself.
//
// Giving each worker its own prefix and granting only that subtree closes
// it. Workers connect with nats.CustomInboxPrefix(InboxPrefix(workerID)) —
// see internal/worker/natsclient. The server needs no matching change: it
// publishes ">" (see [ServerPermissions]), so msg.Respond and JetStream
// PubAcks still reach whichever prefix a worker chose.
func InboxPrefix(workerID string) string {
	return inboxPrefixRoot + workerID
}

// ValidWorkerIDToken reports whether workerID may be used as a single NATS
// subject token — which every worker→server subject and [InboxPrefix]
// require of it.
//
// Worker IDs are UUIDs generated by workerconfig.LoadOrCreateWorkerID, so in
// practice this always holds; it is checked rather than assumed because the
// ID is read from a file an operator can edit, and a token containing "."
// or a wildcard would silently widen the subtree a permission grant covers.
func ValidWorkerIDToken(workerID string) bool {
	if workerID == "" {
		return false
	}
	return !strings.ContainsAny(workerID, ". \t\r\n*>")
}

// WorkerPermissions returns the NATS permissions for one worker.
//
// Every worker→server subject carries the worker's ID as a token precisely so
// that these permissions can bind it. That is not a stylistic choice: NATS
// permissions are static per credential and JetStream does not stamp
// publisher identity onto a message, so a subject scheme keyed only by job
// and task would give no way to express "only this worker's own traffic" —
// the worker's identity has to live in the subject itself.
func WorkerPermissions(workerID string) *natsserver.Permissions {
	return &natsserver.Permissions{
		Publish: &natsserver.SubjectPermission{
			Allow: []string{
				"task.status." + workerID + ".*",
				"task.logs." + workerID + ".*",
				"worker.register." + workerID,
				"worker.heartbeat." + workerID,
				"worker.deregister." + workerID,
				"worker.diag." + workerID,
				"work.lease." + workerID + ".*",
			},
		},
		Subscribe: &natsserver.SubjectPermission{
			Allow: []string{
				// This worker's own reply inboxes, and no other client's —
				// see [InboxPrefix] for why the process-global "_INBOX.>"
				// cannot be granted here. A request/reply lease cannot work
				// without this.
				InboxPrefix(workerID) + ".>",

				// ACCEPTED GAP. Workers subscribe per-task at assignment time
				// (internal/worker/cancel/cancel.go), so a static permission
				// cannot be narrower than the whole subtree: any enrolled
				// worker can observe any task's cancel signals. Narrowing
				// this needs a permission reload per assignment, or a NATS
				// auth callout. Low severity — a cancel message for a task
				// the worker does not hold is inert.
				"task.cancel.>",
			},
		},
	}
}

// ServerPermissions returns the permissions for sqi-server's own broker
// connections, which need the full subject space: the scheduler consumes every
// worker subject and publishes cancels, and the broker's admin connection
// provisions streams.
func ServerPermissions() *natsserver.Permissions {
	return &natsserver.Permissions{
		Publish:   &natsserver.SubjectPermission{Allow: []string{">"}},
		Subscribe: &natsserver.SubjectPermission{Allow: []string{">"}},
	}
}
